### ISSUE TITLE
Context menu not displayed

### ISSUE THREAD

**Issue by samuelet** [mike-kfed/roundcube-thunderbird_labels#27]
Context menu is not displayed on Rc 1.2.0 and contexmenu plugin V2.1.2

**Comment by dsoares** [comment]
Hi,
But this the thunderbird-labels plugin repository, not contextmenu.
Maybe you meant the plugin [contextmenu](https://github.com/JohnDoh/Roundcube-Plugin-Context-Menu) from @JohnDoh.

**Comment by samuelet** [comment]
I meant that the thunderbird-labels integration with the contextmenu plugin ( from @JohnDoh ) does not work.
I expect that the tb_label_enable_contextmenu option enables this. Or am i wrong?

**Comment by mike-kfed** [comment]
branch `arbitrary_labels` is now working with contextmenu plugin again

**Comment by jjellinek** [comment]
How do I see the code change needed to my copy of the master for this issue to fix it please?

**Comment by mike-kfed** [comment]
You merge my branch arbitrary_labels to your master? There is no simple change, I rewrote the whole client code to use coffeescript as a source and many more fundamental things. You can try to understand the diff of my commit that makes the context menu work again, but then you'd have to adopt that to the old way the client worked html/javascript wise. Other option: you test my branch arbitrary_labels, we fix issues if there are any, when it's working fine I merge with my master and make a new release ;)

**Comment by filhocf** [comment]
@mike-kfed , I tried the contextmenu plugin, from Jonh Do, with your branch arbitrary_labels, without success as expected by @jjellinek. Anyway, as I use your plugin through keyboard, are works fine.

In other hand, I tried other situation that I believe to need attention.
When I click over a mail into list board and press 1, by example, the item in the list change to red together with title in the mail board (where we read the email). 
![image](https://user-images.githubusercontent.com/952596/34008560-e1845a56-e0ec-11e7-8354-bb116e197438.png)

But when I click over mail board and press 1, only the title in this board change the color to red. The item list, into list board, not change the color.

![image](https://user-images.githubusercontent.com/952596/34008569-ef9947aa-e0ec-11e7-9b12-2dbb233fa4bd.png)

Is it a bug?

**Comment by sgmacdougall** [comment]
I have RC 1.3.6, context_menu 2.3, and thunderbird_labels 1.1.4.
I have added this to my config.inc.php:

$config['tb_label_enable_contextmenu'] = 'true';

Yet. when I right click on an e-mail, I see no option to add a label.
Am I missing something?

**Comment by mike-kfed** [comment]
you have to use `arbitrary_labels` branch, as mentioned in this thread. Just tested again with RC 1.3.6, context menu master and thunderbird labels `arbitrary_labels` branch

**Comment by sgmacdougall** [comment]
That worked. I did see that in the notes. I thought it might have been merged with the master by now.

Thanks.

**Comment by mike-kfed** [comment]
refactored code in branch `rc1.4beta` works with contextmenu 3.0 and roundcube 1.3.7 and roundcube 1.4beta.
