### ISSUE TITLE
update to rc 1.4 (beta)

### ISSUE THREAD

**Issue by trueshanti** [mike-kfed/roundcube-thunderbird_labels#38]
since this is an essential plugin - we would love to see an update :-)

**Comment by trueshanti** [comment]
some functions are not in sync with rc1.4(beta)

TypeError: rcmail_ui.check_tb_popup is not a function[Weitere Informationen] tb_label.js:73:7
rcm_tb_label_submenu
https://mail.***.com/rc-dev/plugins/thunderbird_labels/tb_label.js:73:7
rcube_webmail/this.command
https://mail.***.com/rc-dev/program/js/app.min.js:66:192
onclick
https://mail.***.com/rc-dev/:1:8

**Comment by mike-kfed** [comment]
Cannot really reproduce that error, please give more detail. works fine for me in 1.4beta with current master. If you are using elastic skin, please try my `rc1.4beta` branch. It technically works there now, but that is a long way off (no styling applied for example)

**Comment by mike-kfed** [comment]
aha, seems to happen when you click on the button in the toolbar menu *and* only in the new elastic skin of 1.4beta. This uses a very different way to show toolbar submenu popups. For now I only keep the console error from happening - workaround: use keyboard shortcuts 1-5 to set labels in this skin or don't use elastic until new popup is implemented.

**Comment by mike-kfed** [comment]
branch `rc1.4beta` works technically with skins classic, larry and elastic for roundcube 1.4beta - enjoy.

**Comment by trueshanti** [comment]
thank you :-)
