### ISSUE TITLE
Is there a way to set labels with sieve (set variable)

### ISSUE THREAD

**Issue by efelon** [mike-kfed/roundcube-thunderbird_labels#45]
Hi,

i was wondering if it is possible to set the labels with a sieve action? There it is possible to write an action like:

`set "variablename" "value";`

A complete example rule:

```
require ["fileinto","variables"];
# rule:[Inbox Test]
if allof (header :contains "subject" "inbox")
{
	fileinto "INBOX";
	set "label" "work";
	stop;
}
```

Since I don't know how the label information is saved, I thought to ask you directly.

Thanks in advance.

**Comment by mike-kfed** [comment]
this is a plugin project page for roundcube and not a SIEVE support forum... however your answer is here (first result of google "sieve imap labels") https://wiki.dovecot.org/Pigeonhole/Sieve/Examples#Flagging_or_Highlighting_your_mail
