### ISSUE TITLE
New Labels in red

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [mike-kfed/roundcube-thunderbird_labels#47]
Hello,
since few versions i note, that when I add a new label inside roundcube, it´s always red independet the label I add.
Labels coming from Thunderbird are in correct color.
Greets

**Comment by mike-kfed** [comment]
I cannot reproduce this, what version of roundcube and tblables plugin are you using exactly, also which theme for roundcube? The colors are coming from a CSS file, maybe this was modified?

**Comment by Sh4d0wF1gh7** [comment]
oh so much sorry. I used v1.1
With current 1.3.2 all is fine
