### ISSUE TITLE
"installed" but not working, greyed out symbol

### ISSUE THREAD

**Issue by luvis** [mike-kfed/roundcube-thunderbird_labels#52]
I installed through 
composer require weird-birds/thunderbird_labels
and it installed and enabled the plugin.

Now I can see a greyed out "Labels" in the menubar of an open email but I can't click it. I opened the settings ->thunderbird label options: and wrote a few names for the empty labels and saved them, but they don't seem to be saved because they are still blank next time I check.
So I don't know if it's a permission error or something.

Also in the installation instructions it says 
add , 'thunderbird_labels' to $rcmail_config['plugins'] in main.inc.php

but I can't find any main.inc.php file. Since I used the composer install command, maybe I don't need to do this step but I thought it was strange. Also I'm using the elastic skin and there doesn't seem to ba an elastic skin in the thunderbird skin folder. however symlinking it to default or larry just creates a very strange and out of place icon, which is still grey and not working.

What have I done wrong?

**Comment by mike-kfed** [comment]
I have never used composer, I assume it installed an old version? see issue #44 you are not the only one having problems with that tool.
therefore I suggest you manually install using the steps found in README and not using composer.

thanks for the main.inc.php hint, indeed that is no longer part of roundcube, it's called `config/config.inc.php` now.

**Comment by luvis** [comment]
Just wanted to let you know that installing it manually worked fine. It's the composer install that messes it up for some reason.
