### ISSUE TITLE
Extra blank space on Elastic theme below each email message listed

### ISSUE THREAD

**Issue by krismach** [mike-kfed/roundcube-thunderbird_labels#55]
Using Elastic theme, there is an extra blank space in email messages list, It's where the bullet would go if the message had a label. But if it doesn't have label, it still takes the extra space. Changing to Thunderbird UI Style for labels, it too has the blank space, even though there would be no bullets since this style changes the color.

**Comment by mike-kfed** [comment]
I commited a CSS fix, please check current master if that's fine for you now. Looks good to me on Firefox, Chrome and Safari.

**Comment by krismach** [comment]
Mike, looks great. Thank you.
