### ISSUE TITLE
elastic issues

### ISSUE THREAD

**Issue by trueshanti** [mike-kfed/roundcube-thunderbird_labels#58]
Hi

1) [thunderbird]-style in elastic-skin (v1.4.9) does not show anything, ( neither in messagelist nor message-view)
2) [bullet]-style does show bullets in list , but nothing in message-view.

i see not errors

fyi&best regards

c-:

**Comment by mike-kfed** [comment]
ad 1. thunderbird style changes the color of the subject in the message list like thunderbird would

ad 1. and 2. - true in elastic skin no thunderbird labels are shown in the message-view, feel free to contribute that feature.

**Comment by mkerstner** [comment]
Hi, in fact using RC 1.5.1 shows a JS error when trying to open the context menu

![tl-error](https://user-images.githubusercontent.com/1525968/144715254-3597282f-acdf-412c-a1ed-88acbd807f87.png)

Happy to contribute if you can provide a hint into the correct here. Thanks

**Comment by mike-kfed** [comment]
using master branch of [johndoh/roundcube-contextmenu](https://github.com/johndoh/roundcube-contextmenu) with RC 1.5.1 and and master branch of my plugin doesn't let me reproduce your issue @mkerstner - sorry I cannot provide a hint, contextmenu works fine for me.

**Comment by mike-kfed** [comment]
message-view shows the labels. closing
