### ISSUE TITLE
Question:  Are the labels saved on the imap server?

### ISSUE THREAD

**Issue by ftoledo** [mike-kfed/roundcube-thunderbird_labels#59]
I'm search if i can tag on thunderbird and see the same label in roundcoube (using imap account)

Thanks!

**Comment by joaquinferrero** [comment]
Yes, Dovecot imap server save tags within the name of email archive:
`1601291185.H634182P16357.aprix.api.net:2,Sag`

The labels in this example are at right of coma: **Sag**. The name of labels are saved at dovecot-keywords archive.

The thunderbird_labels plugin work, but... sometimes Roundcube don't show them.

**Comment by ftoledo** [comment]
Cool! great notice!.

I have dovecot as imap server, also I have a legacy courier too. I will test on both!
I suggest that put this info at some point in the readme.

Thanks for your reply!

Saludos!
