### ISSUE TITLE
Labels applied from search box and with Shift/Ctrl key modifiers

### ISSUE THREAD

**Issue by dapphp** [mike-kfed/roundcube-thunderbird_labels#60]
Hi,

First of all, thank you for the amazing plugin. It's awesome to have TB compatible labels in Roundcube that are shared between clients through IMAP flags.

Recently I noticed a couple of small issues:

1. The keypress event that sets labels do not detect Shift or Ctrl key modifiers. The effect, for example, is that pressing Shift+2 or Ctrl+1 sets or unsets labels on any selected message. I think that it if any key modifiers are set the labels should not be applied.
2. When typing in the Roundcube "search" input field, the keypress events bubble so labels are applied when typing a search. To replicate, highlight one or more messages, click on the search box, type "foo3@..." and labels are applied for the "3" key and "Shift+2" key. If typing in the search box, I don't think labels should be applied.

Do you think it makes sense to fix these features? If so and you don't have time I can attempt the fix and submit a PR.

Thank you!

**Comment by mike-kfed** [comment]
thanks for reporting those issues! can you please try branch `shift-modifiers` to see if that fixes it for you?

**Comment by dapphp** [comment]
Hi Michael,

Thank you for the super quick fix! Sorry for my delay. This indeed does fix the issue. We're not yet on 1.4 so I patched the change into our release and it is all good now. Much appreciated!

Please feel free to close or resolve as you see fit.
