### ISSUE TITLE
Classic skin with desktop layout message list entry height and vertical-align

### ISSUE THREAD

**Issue by urusha** [mike-kfed/roundcube-thunderbird_labels#69]
Roundcube 1.5.3
Classic skin with desktop layout message list entry height is much bigger than it is without plugin and vertical-align of the subject string is not middle.
This is because labels are placed under subject, not on the right (like in larry).
![image](https://user-images.githubusercontent.com/1746504/208664005-dccddfc2-9e84-44b8-8cd5-836f3d908235.png)

**Comment by mike-kfed** [comment]
Then the solution is to switch to larry where it looks right :)
Or make a pull request that improves the situation for the classic skin. I will not invest time in this, as classic skin is not even part of the current default roundcube package anymore.

**Comment by mike-kfed** [comment]
fixed in master, will be included in 1.6.2 release
